name: Build App

on: [push]

jobs:
  Build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Create Build Environment
      shell: bash
      working-directory: ${{github.workspace}}
      run: ./build.sh
